# Generated by Django 6.0.5 on 2026-09-03 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
        ),
        migrations.AddField(
            model_name='doctorabsence',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='users.doctor'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('medicaldocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.medicaldocument')),
                ('dosage', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('appointments.medicaldocument',),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('medicaldocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.medicaldocument')),
                ('target', models.CharField(choices=[('doctor', 'Do lekarza specjalisty'), ('exam', 'Na badanie')], max_length=10)),
                ('exam_name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('appointments.medicaldocument',),
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('medicaldocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.medicaldocument')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            bases=('appointments.medicaldocument',),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.patient'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='doctorabsence',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='absence_end_date_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='doctorabsence',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='absence_end_time_gt_start'),
        ),
        migrations.AddConstraint(
            model_name='doctorabsence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('all_day', True), ('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('all_day', False), ('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR'), name='absence_times_match_all_day'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day_of_week'), name='unique_doctor_day'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='schedule_end_time_gte_start'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='appointments.diagnosis'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='appointments.drug'),
        ),
        migrations.AddField(
            model_name='referral',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='appointments.diagnosis'),
        ),
        migrations.AddField(
            model_name='referral',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='users.specialty'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sick_leaves', to='appointments.diagnosis'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_in_(1-5)'),
        ),
    ]
